#spring.application.name=student-erp-TEST-123
# ===============================
# SERVER CONFIG
# ===============================
server.port=5000

# ===============================
# MYSQL DATABASE (HOSTINGER)
# ===============================


spring.datasource.url=jdbc:mysql://in-mum-web1111.main-hosting.eu:3306/u515790361_student_erp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=u515790361_study
spring.datasource.password=officePUNE@MH12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database=mysql
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.jakarta.persistence.jdbc.url=jdbc:mysql://in-mum-web1111.main-hosting.eu:3306/u515790361_student_erp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# ===============================
# JWT CONFIG
# ===============================
jwt.secret=your-super-secret-random-string-change-this-in-production-abc123xyz789
jwt.expiration=604800000

# ===============================
# PYTHON AI SERVICES
# ===============================
ai.fee-predictor.url=http://localhost:8001
ai.attendance-anomaly.url=http://localhost:8002
ai.exam-predictor.url=http://localhost:8003
ai.query-classifier.url=http://localhost:8004
ai.ocr-service.url=http://localhost:8005
# ===============================
# APP CONFIG
# ===============================
#app.name=Student ERP
spring.application.name=student-erp